### ISSUE TITLE
go函数

### ISSUE THREAD

**Issue by wxb** [wxb/wxb.github.io#40]

**Comment by wxb** [comment]
# 命名函数返回值

```go
func Ta(succ map[string]int64, fail map[string]error) {
    return
}
```

**Comment by wxb** [comment]
> # 命名函数返回值
> ```go
> func Ta(succ map[string]int64, fail map[string]error) {
>     return
> }
> ```

# 返回值不会进行初始化

对于函数的命名返回值，go语言并不会初始化对于命名返回值变量，这里的变量将会是**类型零值**

**Comment by wxb** [comment]
> # 命名函数返回值
> ```go
> func Ta(succ map[string]int64, fail map[string]error) {
>     return
> }
> ```

# 类型零值为`nil`命名返回值，如果在函数中未初始化直接赋值会导致程序panic

例如 map
> https://go.dev/play/p/6QN5PPWfv1z
```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println("Hello, 世界")

	succ, fail := t(false)
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p\n", succ, fail)

	for k, v := range succ {
		fmt.Println(k, v)
	}
	fmt.Println("-----------------------")
	succ, fail = t(true)
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p\n", succ, fail)
}

func t(ok bool) (succ map[string]int64, fail map[string]error) {
	if ok {
		succ["1"] = 1
		fail["2"] = errors.New("2")
	}

	return
}
```

> 结果：
> ```sh
> Hello, 世界
> map[] map[] true true 0 0
> 0x0 0x0
> -----------------------
> panic: assignment to entry in nil map
> 
> goroutine 1 [running]:
> main.t(...)
> 	/tmp/sandbox1318394599/prog.go:28
> main.main()
> 	/tmp/sandbox1318394599/prog.go:21 +0x2ef
> 
> ```
