### ISSUE TITLE
fsnotify

### ISSUE THREAD

**Issue by wxb** [wxb/wxb.github.io#51]
# [fsnotify](https://github.com/fsnotify/fsnotify)

fsnotify is a Go library to provide cross-platform filesystem notifications on
Windows, Linux, macOS, and BSD systems.

fsnotify requires Go 1.16 or newer.

API docs: https://pkg.go.dev/github.com/fsnotify/fsnotify

Usage
-----
A basic example:

```go
package main

import (
	"log"

	"github.com/fsnotify/fsnotify"
)

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
				if event.Has(fsnotify.Write) {
					log.Println("modified file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	err = watcher.Add("/tmp")
	if err != nil {
		log.Fatal(err)
	}
	<-done
}
```

A slightly more expansive example can be found in [cmd/fsnotify](cmd/fsnotify),
which can be run with:

    # Watch the current directory (not recursive).
    $ go run ./cmd/fsnotify .

**Comment by wxb** [comment]
## select 定义
> https://go.dev/ref/spec#Select_statements

A "select" statement chooses which of a set of possible [send](https://go.dev/ref/spec#Send_statements) or [receive](https://go.dev/ref/spec#Receive_operator) operations will proceed. It looks similar to a ["switch"](https://go.dev/ref/spec#Switch_statements) statement but with the cases all referring to communication operations.

## 知识点

- select 的作用是同时监听多个 case 是否可以执行
- select 同时监听，只要有一个case满足时执行改case并退出select，所以select经常与for配合使用
- select 是与 switch 相似的控制结构，与 switch 不同的是，select 中虽然也有多个 case，但是这些 case 中的表达式必须都是 Channel 的收发操作
- select 能在 Channel 上进行非阻塞的收发操作；
- select 在遇到多个 Channel 同时响应时，会随机执行一种情况；

## 面向信仰编程
 [5.2 select](https://draveness.me/golang/docs/part2-foundation/ch05-keyword/golang-select/)

- select 随机执行
```go
func main() {
	ch := make(chan int)
	go func() {
		for range time.Tick(1 * time.Second) {
			ch <- 0
		}
	}()

	for {
		select {
		case <-ch:
			println("case1")
		case <-ch:
			println("case2")
		}
	}
}
```

## for-select时break、continue、goto

- break只能退出select，除非配合标记label跳出for
- continue会作用于for，进行下一次循环
- goto配合label也可以直接跳出for

**Comment by wxb** [comment]
## range

### Map 类型

对于map类型遍历时，如果map没有初始化，只是map类型零值`nil`时，range并不会报错

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println("Hello, 世界")

	succ, fail := t(false)
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p\n", succ, fail)

	for k, v := range succ {
		fmt.Println(k, v)
	}
}

func t(ok bool) (succ map[string]int64, fail map[string]error) {
	if ok {
		succ["1"] = 1
		fail["2"] = errors.New("2")
	}

	return
}
```

> 结果：
> ```sh
> Hello, 世界
> map[] map[] true true 0 0
> 0x0 0x0
> ```

**Comment by wxb** [comment]
## [for 循环](https://go.dev/ref/spec#For_statements)

A "for" statement specifies repeated execution of a block. There are three forms: The iteration may be controlled by a single condition, a "for" clause, or a "range" clause.

## For statements with single condition
> 单个条件

## For statements with for clause
> 分号分隔的子句

### 分号分隔三段：
- init： 一般为赋值表达式，给控制变量赋初值；
- condition： 关系表达式或逻辑表达式，循环控制条件；
- post： 一般为赋值表达式，给控制变量增量或减量。

### 特殊用法
- 缺省init
> 灵活应用：利用for循环外部变量
  ```go
  i := 0
  for ; ; i++ {
      fmt.Println(i)
      if i > 10 {
      break
      }
  }
  ```
- 缺省condition
> 灵活应用：在程序内部指定条件时终止，否则无限循环
  ```go
    for i := 0; ; i++ {
        if i > 10 {
	        break
        }
        fmt.Println(i)
    }
  ```
- 缺省post
> 灵活应用：在程序内部指定条件时终止，否则无限循环
  ```go
  for i := 0; ; {
  fmt.Println(i)
    if i > 10 {
	    break
    }
    i++
  }
  ```

## For statements with range clause
> range遍历

**Comment by wxb** [comment]
## [Function函数](https://go.dev/ref/spec#Function_types)
A function type denotes the set of all functions with the same parameter and result types. The value of an uninitialized variable of function type is nil.

## 命名函数返回值

```go
func Ta(succ map[string]int64, fail map[string]error) {
    return
}
```

## 返回值不会进行初始化

对于函数的命名返回值，go语言并不会初始化对于命名返回值变量，这里的变量将会是**类型零值**

例如对于map类型：

> https://go.dev/play/p/Nd-gBtVmPw5

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println("Hello, 世界")

	succ, fail := t(false)
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p\n", succ, fail)

	for k, v := range succ {
		fmt.Println(k, v)
	}

	succ, fail = tt()
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p", succ, fail)
}

func t(ok bool) (succ map[string]int64, fail map[string]error) {
	if ok {
		succ["1"] = 1
		fail["2"] = errors.New("2")
	}

	return
}

func tt() (map[string]int64, map[string]error) {
	succ := make(map[string]int64)
	fail := make(map[string]error)
	return succ, fail
}
```
结果：
```sh
Hello, 世界
map[] map[] true true 0 0
0x0 0x0
map[] map[] false false 0 0
0xc00010c1e0 0xc00010c210
```

## 类型零值为`nil`命名返回值，如果在函数中未初始化直接赋值会导致程序panic

例如 map
> https://go.dev/play/p/6QN5PPWfv1z
```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println("Hello, 世界")

	succ, fail := t(false)
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p\n", succ, fail)

	for k, v := range succ {
		fmt.Println(k, v)
	}
	fmt.Println("-----------------------")
	succ, fail = t(true)
	fmt.Println(succ, fail, succ == nil, fail == nil, len(succ), len(fail))
	fmt.Printf("%p %p\n", succ, fail)
}

func t(ok bool) (succ map[string]int64, fail map[string]error) {
	if ok {
		succ["1"] = 1
		fail["2"] = errors.New("2")
	}

	return
}
```

> 结果：
> ```sh
> Hello, 世界
> map[] map[] true true 0 0
> 0x0 0x0
> -----------------------
> panic: assignment to entry in nil map
> 
> goroutine 1 [running]:
> main.t(...)
> 	/tmp/sandbox1318394599/prog.go:28
> main.main()
> 	/tmp/sandbox1318394599/prog.go:21 +0x2ef
> 
> ```

**Comment by wxb** [comment]
## slice切片

```go
package main

import (
	"fmt"
	"sync"

	cmap "github.com/orcaman/concurrent-map"
	"github.com/panjf2000/ants/v2"
)

func main() {

	pool, _ := ants.NewPool(500)
	defer pool.Release()

	fmt.Println("-", pool.Cap(), pool.Free(), pool.Running(), pool.Waiting())

	fn := func(i int, succ, fail cmap.ConcurrentMap, wg *sync.WaitGroup) func() {
		return func() {
			defer wg.Done()

			fmt.Println(i)
			succ.Set(fmt.Sprintf("%d", i), i)
			fail.Set(fmt.Sprintf("%d", i), i)

			fmt.Println(&succ)
			fmt.Printf("succ %p, fail %p", &succ, &fail)
			fmt.Println("=", pool.Cap(), pool.Free(), pool.Running(), pool.Waiting())
		}
	}

	succ := cmap.New()
	fail := cmap.New()
	fmt.Println(&succ)
	fmt.Printf("succ %p %p, fail %p %p", succ, &succ, fail, &fail)

	wg := sync.WaitGroup{}
	for i, _ := range make([]int, 2000) {
		wg.Add(1)
		pool.Submit(fn(i, succ, fail, &wg))
	}
	wg.Wait()

	fmt.Printf("succ %p, fail %p", &succ, &fail)
	fmt.Println("*", pool.Cap(), pool.Free(), pool.Running(), pool.Waiting())

	chk := map[int]struct{}{}
	for i, _ := range make([]int, 2000) {
		chk[i] = struct{}{}
	}

	fmt.Println(succ.Count())
	for i, v := range succ.Items() {
		fmt.Println(i, v)
	}

	fmt.Println("++++++++++")

	fmt.Println(fail.Count())
	for i, v := range fail.Items() {
		fmt.Println(i, v)
	}

}

```

**Comment by wxb** [comment]
## new和make 定义
- [make](https://pkg.go.dev/builtin@go1.18.3#make)
> The make built-in function allocates and initializes an object of type slice, map, or chan (only). Like new, the first argument is a type, not a value. Unlike new, make's return type is the same as the type of its argument, not a pointer to it. 
- [new](https://pkg.go.dev/builtin@go1.18.3#new)
> The new built-in function allocates memory. The first argument is a type, not a value, and the value returned is a pointer to a newly allocated zero value of that type.

## new 分配内存
https://go.dev/ref/spec#Allocation

## make 创建slice、map和channel
https://go.dev/ref/spec#Making_slices_maps_and_channels

**Comment by wxb** [comment]
## iota常量

iota 文档 https://go.dev/ref/spec#Iota

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/7111495/177548940-d0530936-c4ea-4243-b004-ebfe312719b4.png">

> 在一个常量声明中，预先声明的标识符 iota 代表连续的无类型的整数常量。它的值是该常量声明中各 ConstSpec 的索引，从0开始

## [Go 为什么要设计 iota 常量？](https://mp.weixin.qq.com/s/hMCzZQ0j74X9Yvd0nSJR0w)

- iota 关键字表示从 0 开始的整数常量；在作用上可以简化使用自动递增数字的常量定义

## iota 常用于以下的场景：

- 作为和与算法中的迭代器。
- 作为下标索引。
- 用于复数的虚数部分。

## 示例
```go
const (
	c0 = iota  // c0 == 0
	c1 = iota  // c1 == 1
	c2 = iota  // c2 == 2
)

const (
	a = 1 << iota  // a == 1  (iota == 0)
	b = 1 << iota  // b == 2  (iota == 1)
	c = 3          // c == 3  (iota == 2, unused)
	d = 1 << iota  // d == 8  (iota == 3)
)

const (
	u         = iota * 42  // u == 0     (untyped integer constant)
	v float64 = iota * 42  // v == 42.0  (float64 constant)
	w         = iota * 42  // w == 84    (untyped integer constant)
)

const x = iota  // x == 0
const y = iota  // y == 0

const (
	bit0, mask0 = 1 << iota, 1<<iota - 1  // bit0 == 1, mask0 == 0  (iota == 0)
	bit1, mask1                           // bit1 == 2, mask1 == 1  (iota == 1)
	_, _                                  //                        (iota == 2, unused)
	bit3, mask3                           // bit3 == 8, mask3 == 7  (iota == 3)
)
```
